"""Conformance of compute_zmanim() against the library it was derived from.

Values come from KosherJava 2.5.0's own output, committed at
tests/data/zmanim_golden.csv.gz and regenerated by
tools/zmanim_golden/generate.py. Neither Java nor a network is needed here.

The full table is 40 cities x 1,461 days x 18 zmanim, over a million
comparisons, and sweeping all of it costs about six seconds -- most of the
suite's total runtime, on every run, to re-prove something that only changes
when the zmanim code changes. So the build sweeps a fixed sample spanning every
city and every season, which is fast and still catches a definition that moved.
The exhaustive sweep is one environment variable away:

    ZMANIM_FULL_REFERENCE=1 python -m pytest tests/test_zmanim_reference.py

Run it when touching src/smart_kosher/zmanim, changing a city, or regenerating
the table. CI should run it on those paths.

This exists because the divergences it now forbids were all silent. Sunset was
computed at sea level for cities standing 780 m up, Shabbat exit was a flat 36
minutes that only matched the real angle at the equinox, and solar midnight was
noon plus twelve hours on a day that is not twenty-four hours long. Nothing in
the old suite could see any of it, because every assertion was written against
what the code already did.
"""

import csv
import gzip
import os
import unittest
from pathlib import Path

from smart_kosher.data import load_cities
from smart_kosher.zmanim import compute_zmanim

GOLDEN = Path(__file__).parent / "data" / "zmanim_golden.csv.gz"

FULL_SWEEP = bool(os.environ.get("ZMANIM_FULL_REFERENCE"))

# Every Nth row of the table. Prime, and coprime with the 1,461-row block each
# city occupies, so the sampled dates walk through the seasons instead of
# landing on the same week of every year.
SAMPLE_STRIDE = 97

# Our key -> the reference column it must equal.
#
# tset_hakohavim_shabbat maps to the same column as tset_hakohavim on purpose:
# the reference has a single tzais, and Shabbat exit is our name for it.
REFERENCE_COLUMNS = {
    "alot_hashachar": "alos_16_1",
    "talit_and_tefillin": "misheyakir_11_5",
    "netz_hachama": "sunrise_elev",
    "sof_zman_shema_gra": "sof_zman_shma_gra",
    "sof_zman_shema_mga": "sof_zman_shma_mga",
    "sof_zman_tfilla_gra": "sof_zman_tfila_gra",
    "sof_zman_tfilla_mga": "sof_zman_tfila_mga",
    "chatzot_hayom": "chatzos",
    "mincha_gedola": "mincha_gedola",
    "mincha_gedola_30min": "mincha_gedola_30",
    "mincha_ketana": "mincha_ketana",
    "plag_hamincha": "plag_hamincha",
    "shkia": "sunset_elev",
    "tset_hakohavim": "tzais_8_5",
    "tset_hakohavim_shabbat": "tzais_8_5",
    "tset_hakohavim_rabeinu_tam": "tzais_72",
    "chatzot_halayla": "solar_midnight",
    "candle_lighting": "candle_18",
}

# The reference file stores tenths of a second, so 0.05 s of the budget is
# already spent on rounding. Both implementations run the same NOAA algorithm:
# anything above this is a definition that drifted, not arithmetic noise.
TOLERANCE_SECONDS = 1.0


class ReferenceConformanceTests(unittest.TestCase):
    def _sweep(self, stride):
        """Compare against the table, keeping the worst delta per zman."""
        cities = load_cities()
        worst = {}
        rows = 0
        seen_cities = set()

        with gzip.open(GOLDEN, "rt", encoding="utf-8") as handle:
            for index, row in enumerate(csv.DictReader(handle)):
                if stride > 1 and index % stride:
                    continue
                city = cities[row["city"]]
                year, month, day = (int(part) for part in row["date"].split("-"))
                computed = compute_zmanim(
                    year, month, day,
                    city["lat"], city["lon"], city["elevation"],
                )
                rows += 1
                seen_cities.add(row["city"])

                for key, column in REFERENCE_COLUMNS.items():
                    # Seconds from UTC midnight on both sides, so the comparison
                    # never touches a time zone or a DST rule.
                    delta = abs(computed[key] * 60.0 - float(row[column]))
                    if delta > worst.get(key, (0.0,))[0]:
                        worst[key] = (delta, row["city"], row["date"])

        return rows, seen_cities, worst

    def _assert_within_tolerance(self, worst):
        failures = [
            "{}: {:.3f}s off at {} on {}".format(key, delta, city_id, date)
            for key, (delta, city_id, date) in sorted(worst.items())
            if delta > TOLERANCE_SECONDS
        ]
        self.assertEqual([], failures, "\n".join(failures))
        self.assertEqual(
            set(REFERENCE_COLUMNS), set(worst), "a zman was never compared")

    def test_sampled_days_match_the_reference_library(self):
        rows, seen_cities, worst = self._sweep(SAMPLE_STRIDE)

        # A sample that quietly stopped covering a city would still pass every
        # tolerance check, so the coverage is asserted rather than assumed.
        self.assertEqual(set(load_cities()), seen_cities)
        self.assertGreater(rows, 400, "sample looks too thin to mean anything")
        self._assert_within_tolerance(worst)

    @unittest.skipUnless(
        FULL_SWEEP, "set ZMANIM_FULL_REFERENCE=1 for the exhaustive sweep")
    def test_every_day_matches_the_reference_library(self):
        rows, _, worst = self._sweep(1)

        self.assertGreater(rows, 50000, "golden table looks truncated")
        self._assert_within_tolerance(worst)

    def test_golden_table_covers_every_packaged_city(self):
        # A city added to cities.json without regenerating the table would
        # otherwise be silently unverified.
        with gzip.open(GOLDEN, "rt", encoding="utf-8") as handle:
            covered = {row["city"] for row in csv.DictReader(handle)}
        self.assertEqual(set(load_cities()), covered)

    def test_golden_table_columns_are_all_consumed(self):
        # Guards the mapping itself: a renamed reference column has to fail here
        # rather than quietly stop being compared.
        with gzip.open(GOLDEN, "rt", encoding="utf-8") as handle:
            header = set(csv.DictReader(handle).fieldnames) - {"city", "date"}
        # sunrise_sea and sunset_sea are inputs the product never exposes as a
        # zman of their own; everything else must be claimed by a real key.
        self.assertEqual(
            set(REFERENCE_COLUMNS.values()) | {"sunrise_sea", "sunset_sea"},
            header,
        )


if __name__ == "__main__":
    unittest.main()
