/*
 * Wire envelope for the S3<->H2 link: "<crc32hex> <json>\n".
 *
 * Deliberately free of ESP-IDF, FreeRTOS and cJSON so it builds and is tested
 * with plain gcc on the host (see ../host_test). The line assembler and the
 * frame validator are where the historic silent-drop bugs lived, so they are
 * exactly the parts worth testing off-device.
 *
 * The CRC is a standard reflected CRC-32 (the same one binascii.crc32 and
 * esp_crc32_le compute); host tests pin it against vectors generated by the
 * Python side, which is the other end of this wire.
 */

#ifndef H2_PROTOCOL_H
#define H2_PROTOCOL_H

#include <stdbool.h>
#include <stddef.h>
#include <stdint.h>

/* A ping ack carries the capability list plus eleven health counters and lands
 * around 520 bytes, so the old 512 would have truncated it -- into JSON that
 * is invalid but still correctly checksummed, which reads on the hub as a
 * coordinator that never answers a ping at all. Sized with room to spare, and
 * link.c refuses to send anything that would not fit rather than truncating. */
#define PROTO_MAX_LINE 1024

uint32_t proto_crc32(const void *data, size_t len);

/* Result of validating one assembled line. */
typedef enum {
    PROTO_FRAME_OK = 0,
    PROTO_FRAME_BAD_PREFIX, /* missing/short/non-hex crc prefix */
    PROTO_FRAME_BAD_CRC,    /* prefix parsed, checksum disagrees */
} proto_frame_status_t;

/*
 * Split "<crc32hex> <body>" in place. On PROTO_FRAME_OK, *body points into
 * ``line`` at the JSON body (``line`` is modified: the separator becomes NUL).
 * A malformed prefix and a bad checksum are distinguished because the sender
 * deserves a different answer for each -- returning nothing for either is what
 * made a mangled command look like silence.
 */
proto_frame_status_t proto_frame_body(char *line, const char **body);

/*
 * Incremental line assembler.
 *
 * ``overrun`` latches when a line exceeds the buffer, and everything up to the
 * next newline is then discarded. Resetting the length without that latch --
 * what the original reader did -- turned one overlong line into a second,
 * bogus frame built from its tail.
 */
typedef struct {
    char   buf[PROTO_MAX_LINE];
    size_t len;
    bool   overrun;
} proto_lines_t;

void proto_lines_init(proto_lines_t *asm_);

/*
 * Feed one byte. Returns true when a complete, non-empty line is ready in
 * ``asm_->buf`` (NUL-terminated, CR stripped); the caller must consume it
 * before the next call. Lines dropped by overrun never return true, and
 * increment *dropped when it is non-NULL.
 */
bool proto_lines_feed(proto_lines_t *asm_, char ch, uint32_t *dropped);

#endif /* H2_PROTOCOL_H */
